### ISSUE TITLE
Add support for authentication of connections

### ISSUE THREAD

**Issue by fehmicansaglam** [tumblr/colossus#116]
I think this may be a general ticket for all protocols. Authentication in MongoDB is a 2 step process. It requires 2 serial requests to authenticate a connection. This means that there should be a pool of stateful connections. Connection pools can be created using LoadBalancingClient. Do you think it is also possible to authenticate them with a given authentication strategy?

http://docs.mongodb.org/meta-driver/latest/legacy/implement-authentication-in-driver/

**Comment by DanSimon** [comment]
I noticed we'll have a similar issue with MySQL.  We could possibly add a new `ConnectionStatus` called `Authenticating` or `Handshake`, which could indicate that the client is connected, but not yet ready to use.   Then we'd have something like an authentication strategy for the protocol that would return a `Callback` that, when complete, would indicate that authentication succeeded/failed.

**Comment by benblack86** [comment]
Closing due to being old and we don't currently support mongoDB or MySql.
