### ISSUE TITLE
0.6.0-M3 is not found on Maven central

### ISSUE THREAD

**Issue by fehmicansaglam** [tumblr/colossus#130]
This release is not present on Maven Central:
https://repo1.maven.org/maven2/com/tumblr/colossus_2.11/

Is it about cache?

**Comment by DanSimon** [comment]
Sorry about that, sonatype was having issues when I tried releasing it yesterday.  I tried again just now and it appears to have worked so it should be available shortly.

**Comment by fehmicansaglam** [comment]
Yes, it's available now. Thanks.
