### ISSUE TITLE
New Parallel Service Layer

### ISSUE THREAD

**Issue by DanSimon** [tumblr/colossus#184]
A Parallel or multiplexed service uses a protocol that allows responses to be returned in any order.  Whereas the current service layer is queue-backed and responses must be returned in the same order as the requests were sent, the parallel service layer will be hashmap-backed and every request will have a unique id determined by the client.  So when responses are returned, the id is somehow included in the response and the client can determine which request the response is for.

This means that the protocol must be able to support multiplexing.  For example, Http 1.0 and 1.1 cannot be natively multiplexed, nor can the redis or memcache protocols.  What we can do, however, is create our own protocol to wrap any existing protocol to add multiplexing support.  Of course this means that both the client and server must implement the wrapper protocol, but our primary use case for parallel services is more efficient service to service communication.

So we'll be slightly generalizing the service layer and having two implementations, one for regular services and one for multiplexed services.  We'll also be creating a very simple multiplexing wrapper protocol.

**Comment by hepin1989** [comment]
seems like what vert.x's eventbus's implementation

**Comment by DanSimon** [comment]
There might be some similarities, but vert.x's event bus is more of a high-level pub/sub and clustering system with an actual event bus.  This is more of just a more efficient transport mechanism for two applications to communicate with each other directly.  It could certainly be the basis of a pub/sub system, though that's not our main use case at the moment.

**Comment by benblack86** [comment]
Closing since this is very old.

**Comment by DanSimon** [comment]
Also this was partially done in 0.9, and will be needed in some form for http/2, though I think we'll just take the time and properly re-spec exactly what is needed.
