### ISSUE TITLE
Query String parameters without values causes ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by newfurniturey** [tumblr/colossus#209]
If you're running an HTTP service w/ colossus and hit the service via a URL that contains query string parameters that have no values set, such as:

    http://www.example.com/page?debug

an `ArrayIndexOutOfBoundsException` is thrown:

> java.lang.ArrayIndexOutOfBoundsException: 1
>   at colossus.protocols.http.HttpHead$$anonfun$parseParameters$1.apply(Header.scala:212)
>   at colossus.protocols.http.HttpHead$$anonfun$parseParameters$1.apply(Header.scala:210)
>   at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
>   at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
>   at colossus.protocols.http.HttpHead$.parseParameters(Header.scala:210)[WARN] [06/09/2015 16:12:19.822] [COLOSSUS-server-dispatcher-10] [akka://COLOSSUS/user/devprog-manager/worker-4] Unknown Error! : java.lang.ArrayIndexOutOfBoundsException: 1
>   at colossus.protocols.http.HttpHead.<init>(Header.scala:163)
>   at colossus.protocols.http.HttpRequestParser$$anonfun$httpHead$1.apply(HttpRequestParser.scala:29)
>   at colossus.protocols.http.HttpRequestParser$$anonfun$httpHead$1.apply(HttpRequestParser.scala:28)
>   at colossus.parsing.Combinators$Parser$$anon$3$$anonfun$parse$2.apply(Parsing.scala:230)
>   at scala.Option.map(Option.scala:146)
>   at colossus.parsing.Combinators$Parser$$anon$3.parse(Parsing.scala:230)
>   at colossus.parsing.Combinators$Parser$$anon$4.parse(Parsing.scala:244)
>   at colossus.parsing.Combinators$$anon$7$$anonfun$parse$6.apply(Parsing.scala:295)
>   at colossus.parsing.Combinators$$anon$7$$anonfun$parse$6.apply(Parsing.scala:295)
>   at colossus.parsing.ParserSizeTracker.track(Parsing.scala:57)
>   at colossus.parsing.Combinators$$anon$7.parse(Parsing.scala:295)
>   at colossus.protocols.http.BaseHttpServerCodec.decode(HttpServerCodec.scala:17)
>   at colossus.controller.InputController$class.receivedData(InputController.scala:122)
>   at colossus.controller.Controller.receivedData(Controller.scala:87)
>   at colossus.core.Connection.handleRead(Connection.scala:197)
>   at colossus.core.Worker.selectLoop(Worker.scala:441)
>   at colossus.core.Worker$$anonfun$accepting$1.applyOrElse(Worker.scala:178)
>   at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
>   at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
>   at akka.actor.Actor$class.aroundReceive(Actor.scala:465)
>   at colossus.core.Worker.aroundReceive(Worker.scala:120)
>   at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516)
>   at akka.actor.ActorCell.invoke(ActorCell.scala:487)
>   at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254)
>   at akka.dispatch.Mailbox.run(Mailbox.scala:221)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
>   at java.lang.Thread.run(Thread.java:722)

Sample codeblock to reproduce:

    Service.serve[Http]("dev-prog", config.servicePort) { context =>
        context.handle { connection =>
            connection.become {
                case req @ Get on Root => req.ok(s"Hi, from: ${req.head.url}")
            }
        }
    }

**Comment by DanSimon** [comment]
Which version of Colossus are you on?  #206 , which is in 0.6.3, should have fixed this.

**Comment by DanSimon** [comment]
@newfurniturey can you confirm if the latest stable release fixes your issue?  If so then I'll close this.

**Comment by newfurniturey** [comment]
My apologies for the delay, been offline for a bit - but yeah, the 0.6.3 update _did_ fix the issue! Blindly missed that when testing =[

Thanks for the followup =]
