### ISSUE TITLE
Streaming requests, responses

### ISSUE THREAD

**Issue by DanSimon** [tumblr/colossus#29]
Right now, when reading a request or producing a response, the entire object must be loaded in memory before it can be used.  This isn't really a big deal for small requests, but if we wanted to build, say, an image CDN, the service would need to load the entire image into memory before sending it back.  

So we need to add support for streaming responses.  This would mostly involve changing how the `DataBuffer` works, probably by turning it into a trait and having a callback for "more data is ready".

**Comment by nsauro** [comment]
Can we mark this as resolved?
