### ISSUE TITLE
ServiceClient does not use the provided TagDecorator when reporting metrics

### ISSUE THREAD

**Issue by bnullian** [tumblr/colossus#290]
Internally, it formulates `hTags` and `hpTags` and uses those instead. 

```scala
private val hpTags: TagMap = Map("client_host" -> address.getHostName, "client_port" -> address.getPort.toString)
private val hTags: TagMap = Map("client_host" -> address.getHostName)
```

**Comment by nsauro** [comment]
This one is a bit tricky.  THe main reason being that TagDecorator wants both a Request and a Response, and in ServiceClients, there are only a few instances when we have both.  To do this ticket, I will need to create a new data structure within ServiceClient which holds deferred values for metrics.  When both req/res are handy, we would then get the values out of this data structure, and then go through and tick all the metrics, using the TagDecorator to provide tags.

**Comment by nsauro** [comment]
Ok, so I lied.  There was only one Metric (queueTime) that had that characteristic, which was easily fixable.
