### ISSUE TITLE
Make error reporting more configurable

### ISSUE THREAD

**Issue by DanSimon** [tumblr/colossus#414]
This is spawning from the fact that right now for exceptions that are built into colossus, such as `DroppedReplyException`, we currently print out the entire stack trace which is pretty much useless in those situations.  

We already have a `RequestFormatter` that is used to format requests when being output in an error message, but I think it makes more sense to allow even more flexibility by providing a way to completely control if/how errors are reported.

**Comment by onesupercoder** [comment]
Hey @DanSimon this project is amazing, thank you for making it!  👍   I was wondering if the error reporting configuration is solved in the develop Branch with the new GenRequestHandler you made which provides an unhandledError function to capture errors.  I am new to Scala and am not entirely sure what I am saying.  Could i possibly help by testing the develop branch or some other version or adding tests somewhere?

**Comment by DanSimon** [comment]
Hey @onesupercoder , you're correct that this is somewhat solved in the develop branch, although it's not quite as complete as I would like.  You are able to override the `unhandledError`function, but that only includes errors that occur while processing a request.  Other errors, including `DroppedReplyException`, can occur after request processing so they won't be caught there.  

I'm thinking more along the lines of creating a few mixin traits for various exception types that can instruct the logger on how much information to dump.  An exception like `DroppedReplyException` doesn't benefit from printing a stack trace (since it's always happening in the exact same spot), whereas it would be more useful for some exception thrown by your own code.

This probably won't make it into 0.9.0 since we're already in the release candidate phase and trying to avoid code changes that aren't direct bug fixes, but we'll try to work it into 0.9.1 which shouldn't be far behind.

**Comment by onesupercoder** [comment]
Makes sense, thank you so much @DanSimon!
