### ISSUE TITLE
AsyncServiceClient infinite retry loop

### ISSUE THREAD

**Issue by nsauro** [tumblr/colossus#42]
If an AsyncServiceClient fails to connect,  a race condition can arise where the underlying Worker will send the AsyncServiceClient's proxy actor a "MessageDeliveryFailed", which in turn the Proxy will send back to the Worker.

**Comment by DanSimon** [comment]
Quick update to this issue.  I believe point 1 in my previous comment has since been fixed and was due to the fact that clients could not receive messages while reconnecting, which was solved by separating the connection logic from the worker binding logic.

The second point is still an issue.
