### ISSUE TITLE
Websocket server fails to send lots of small messages (or one large message)

### ISSUE THREAD

**Issue by baank** [tumblr/colossus#424]
Testing with master + pull request #420 and standard HTML5 JS WebSocket API.

``
var str = ""
for (i <- 1 to 51) {
  str += "x"
  println(s"$i-${str.length}")
  sendMessage(s"$i-$str")
}
``

The client will stop receiving messages beyond i=50. This corresponds to the output buffer size set within the BaseWebsocketHandler. This is a contrived example but the real problem is that you can't send large messages e.g. a JSON string to the client at all.

**Comment by DanSimon** [comment]
Thanks for bringing this up, obviously we haven't done too much with the websocket api yet so I'm glad to get some feedback.  I think there's a few different issues happening here.  First, the output buffer size of 50 is entirely arbitrary and definitely way too small.  It should definitely not be hardcoded like that and can easily have a much larger default value.  I've already fixed this in another branch targeted for colossus 0.9, but I'll work to backport to master it so we can publish a fixed build sooner.

Second, the websocket handler doesn't have a good mechanism to deal with output backpressure.  Normally when pushing messages you can attach a callback function to run once the message has been sent, but that's been hidden in the websocket API.  I will look at improving this.

Lastly, I suspect there's a bug in the websocket frame encoding that is causing problems when sending large messages.  I will do what I should have done before and write more tests to figure out what's going on :)  If I can figure this out quickly enough I'll just merge them into #420
