### ISSUE TITLE
Provide a mechanism for cross-worker resource management

### ISSUE THREAD

**Issue by DanSimon** [tumblr/colossus#425]
So in a whole bunch of places in colossus there are settings to limit the sizes of buffers or other resources like request processing concurrency.  These settings are always per-connection or per-request-handler, and in practice that is usually sufficient.  But it can create issues if for example the workload for a service varies highly across connections.  With a per-connection limit you end up either being too restrictive to a single connection or not restrictive enough across a whole service.  I think it shouldn't be too hard to allow these settings to be global, so if we set a global concurrency limit of 100 it can be enforced across workers or across an entire service.  

This should be pretty easy to do with our trusty friend `AtomicLong`, which has proven to work extremely well for this kind of stuff and introduces very little overhead.  Still, I think we can do one step better and allow the user to choose how the limit is enforced.

I'm envisioning a new `Limit` ADT that looks like:

``` scala
trait ActiveLimit {
  def atLimit: Boolean
  def value: Long
  def limit: Limit
}

sealed trait Limit {
  def apply()(implicit system: IOSystem): ActiveLimit
}
case class Local(limit: Long) extends Limit
case class Shared(name: String, limit: Long) extends Limit
```

Every configuration setting would then be a `Limit` and the user can choose whether to use a `Local` limit, which would have the current behavior, or a `Shared` limit which is name-based and managed by the `IOSystem`.  Since shared limits are name-based, it provides a lot of flexibility to users to determine if they want one limit per service, or maybe one per worker or possibly different limits for the same service based on some other parameter.

**Comment by benblack86** [comment]
Is this still a thing?

**Comment by benblack86** [comment]
Closing as not sure on the use case.
