### ISSUE TITLE
Consider using monomorphic types for clients

### ISSUE THREAD

**Issue by DanSimon** [tumblr/colossus#438]
So right now `Http.client`returns a `HttpClient[Callback]` and `Http.futureClient` returns `HttpClient[Future]`.  This is nice because it means that a http client has the same API regardless of whether you're using it in-thread or externally.

On the downside though, we now have higher-kinded types in the basic API for using clients.  This may be confusing and also somewhat seems like an unnecessary exposure of implementation details.  While it does allow people to write generic code that works with both callbacks and futures, this isn't a common use case.

Further, apparently Mockito doesn't play nice with higher-kinded types, so right now it's impossible to mock clients with mockito (haven't tested scalamock yet).

It might be better to have the API return monomorphic subtraits like `HttpCallbackClient` and `HttpFutureClient`, although in that case we'd probably just call the Callback version `HttpClient`.

We'd also have to figure out if we'd do this for any other types that use `Async` typeclass.

**Comment by DanSimon** [comment]
I was able to get Scalamock working with `HttpClient[Callback]`, although I had to change `LiftedClient`from a class to a trait and then create a `BasicLiftedClient`, so that `HttpClient` doesn't extend any classes.

This doesn't fully address this issue, but it's worth doing regardless, so I'll have a PR open soon.

**Comment by aliyakamercan** [comment]
Hey @DanSimon, do you still have the code in some branch I can look at?

**Comment by DanSimon** [comment]
So everything in my last comment was merged in a long time ago.  Scalamock works with HttpClient (and there's a [test](https://github.com/tumblr/colossus/blob/master/colossus-tests/src/test/scala/colossus/service/ServiceClientSpec.scala#L520) for it).

I do recall also attempting to implement the monomorphic types, but I ran into some complexity with the client factories (can't remember the specifics).  It may no longer be an issue since we did just clean some of that up.

But I'm actually no longer a huge fan of making traits called `HttpCallbackClient` and `HttpFutureClient`.  This issue was made before a lot of the work that happened in 0.9.0.  Open to suggestions, but I'm leaning towards scoping them in sub-packages and just having both called `HttpClient`:

```scala
trait AsncHttpClient[M[_]] { //what currently is HttpClient
}

package object futureclient {
  type HttpClient = AsyncHttpClient[Future]
  object HttpClient extends CodecClientFactory //...
}
package object callbackclient {
  type HttpClient = AsyncHttpClient[Callback]
  object HttpClient extends CodecClientFactory //...
}
```
My reasoning is at any given moment you're only going to be using one or the other.  Only in some really bizarre non-standard situation would you have a callback and future clients both in scope.  So it should be totally obvious from the context which `HttpClient` you're actually using.

If we're just using type aliases then I suppose we could also create aliases like `HttpCallbackClient`.  Interested to hear other opinions.

**Comment by benblack86** [comment]
If the original problem has been fixed, I'm not sure if there any worth in changing it as you have suggested. I'm not sure there is a winning argument either way. Am I missing something, or can this issue be closed?

**Comment by DanSimon** [comment]
I'll close for now since I agree this isn't a really a big problem now, but will spend some time experimenting with what I described above.
