### ISSUE TITLE
Do metrics work in 0.8.1?

### ISSUE THREAD

**Issue by hntd187** [tumblr/colossus#447]
The documentation seems outdated and the code doesn't seem to provide any obvious way to report metrics once you've spun up a MetricSystem. The most I can get to function is 

``` scala
val reporter = MetricReporter(
  MetricReporterConfig(Seq(LoggerSender)),
  system.actorOf(Props(classOf[IntervalAggregator], 5 seconds, Agent(MetricMap.Empty), Some(metricSystem / "sys"))),
  "Stufff"
)
```

And those report fine, but using anything else or trying to create my own custom Metrics don't seem to work at all.

**Comment by DanSimon** [comment]
Ah thanks for point that out.  The section in the docs on reporting was indeed out of date.  I've updated them to reflect the latest release and it should make it more clear what to do.  I also realize there's no published scaladocs for the metrics library and I'm working to fix that.

Basically you don't actually need to create your own reporter or manually spin up any actors, just call the `.report` method on an existing `CollectionInterval` of a  `MetricSystem`, and then all metrics created under that system will get reported according to the frequency of that interval.

Let me know if you get it working or if you get stuck on something.

**Comment by hntd187** [comment]
Hey Dan, that works fine, it just did not seem like the collectionIntervals was meant to be messed with, but is there a way to add intervals to this map? I assume it's done via the config, but can it be done in code?

**Comment by DanSimon** [comment]
Ah yeah that's a good point, and I agree it doesn't look intuitive.

You can specify collection intervals either through overriding the defaults in your application.conf (see the [reference.conf](https://github.com/tumblr/colossus/blob/master/colossus-metrics/src/main/resources/reference.conf#L13)), or by passing in a `MetricSystemConfig` object to the `MetricSystem` when you create it.    So in both cases they need to be set when the system is created.
