### ISSUE TITLE
Add a way to intialize collectors for specific tagmaps

### ISSUE THREAD

**Issue by DanSimon** [tumblr/colossus#449]
Normally when a metric is created, it will not report anything until values are added to it.  We can't simply start reporting 0 since we don't know what tag key/values will be used, but in many cases we use metrics without any tags or with a known set of fixed tags.  In those cases it would be nice to be able to force collectors to start immediately reporting 0, so we don't have gaps in the resulting time-series data when services are restarted.

I see two possible ways to address this:
1.  Give every collector some kind of "touch" or "reset" function that accepts a `TagMap`.  This would essentially create a 0 value for the given tagmap.
2.  Add an `initialZeros` configuration setting that accepts a sequence of `TagMap`s and basically does the 1. itself.

Or we could do both.

**Comment by benblack86** [comment]
I'd vote to close this until we have a better use case. If we have a metric that tends to be zero, then we use a counter and set it to zero on service startup. It is occasionally annoying when a new service doesn't report /errors, but it usually resolves itself :)

cc @aliyakamercan
