### ISSUE TITLE
Investigate Non-terminable Pipes

### ISSUE THREAD

**Issue by DanSimon** [tumblr/colossus#479]
Currently in `develop` we're now using pipes as the primary method of interaction between the various layers of a connection handler.  This is working extremely well for handling backpressure compared to the myriad of methods and variables that used to exist.  However pipes have the ability to be both closed or terminated, and these do not seem like features we want to have here.

We already have the circuit-breaker to handle things like preventing sending of messages when not connected, and adding additional logic for closed/terminated on top of that feels like we then have 2-3 different solutions to the same problem.

Therefore it might be worthwhile to create a new trait that has a similar interface without the closed/terminated states.  I imagine that this would also be considerably simpler and possibly faster since there are fewer states to deal with.

**Comment by benblack86** [comment]
Closing since this is very old.
