### ISSUE TITLE
Service Clients should use an implicit metric namespace

### ISSUE THREAD

**Issue by DanSimon** [tumblr/colossus#482]
Right now `ServiceClient` is using the worker's namespace as its namespace.  It should be using an implicitly provided namespace instead.

Clients already require an implicit parameter, either a `WorkerRef` or an `IOSystem` depending on whether you're creating a callback or future-based client.  Having two implicits is starting to make things a bit more complicated, so we should also investigate if there's a way we can easily combine them into a single sort of "client environment" parameter without too much boilerplate or complexity.

**Comment by dxuhuang** [comment]
@DanSimon @benblack86  Is this still relevant? How much of the info here is still true? I'm looking at `ServiceClient` here and the only implicit parameter I see passed into its constructor is a `TagDecorator`. At least at first glance, I'm not sure where else to find a namespace to pass into it.

**Comment by benblack86** [comment]
I believe it is referring to this implicit: https://github.com/tumblr/colossus/blob/master/colossus/src/main/scala/colossus/service/ServiceClient.scala#L192

However, not sure why having it passed by the client would be useful.
