### ISSUE TITLE
Remove dependency on akka-agent

### ISSUE THREAD

**Issue by DanSimon** [tumblr/colossus#492]
We use akka-agent in a few small places.  Currently there is still no artifact available for scala 2.12 and apparently they plan to deprecate it anyway.  Therefore we should replace it with regular atomic references or some other solution.

**Comment by malibuworkcrew** [comment]
@DanSimon I'm thinking about taking a crack at this as we'd like to use colossus with the latest akka. Have you taken another look at the issue since filing this, or do you have more insights/opinion about how you'd like to see agents replaced (especially for Workers)?

**Comment by benblack86** [comment]
I haven't looked into this yet, but I'd recommend if you want to do the work, to branch from the develop branch (v0.9). We are currently trying to release 0.9 version in the next few months. However, you should be able to upgrade to akka without needing to change colossus. We are using 	akka 2.4.17 in most of our services.

**Comment by malibuworkcrew** [comment]
Thanks for getting back, we're currently using akka 2.5.+ with an exclusion on colossus so going to 2.4 we'd still need it. We may keep using the exclusion and come back to the akka-agent work later.

**Comment by benblack86** [comment]
Split this issue into three separate issues. Planning on doing this work over the next 2 weeks.
