### ISSUE TITLE
Make Websocket origin header optional

### ISSUE THREAD

**Issue by labe-me** [tumblr/colossus#496]
Looks like this line prevents connections of websockets without origin header, and rejects non-browser clients. 

https://github.com/tumblr/colossus/blob/e517a42080c4479385d279894982a6c02eb1b3d4/colossus/src/main/scala/colossus/protocols/websocket/Websocket.scala#L40

**Comment by shmishleniy** [comment]
add pull request https://github.com/tumblr/colossus/pull/501

**Comment by benblack86** [comment]
Released in 0.8.4
