### ISSUE TITLE
Possibility to reuse address

### ISSUE THREAD

**Issue by sergP80** [tumblr/colossus#498]
Is there a posibility to reuse address, i.e. so-reuse-addr?

**Comment by DanSimon** [comment]
Not currently, but I think we should allow that and possibly some other [server socket options](https://docs.oracle.com/javase/7/docs/api/java/net/StandardSocketOptions.html) to be set.  I'll look into this a bit more and figure out exactly what we should support.

**Comment by benblack86** [comment]
Can I get some more details on this? Is the idea that we allow server socket options to be set:

For example, adding to [Server](https://github.com/tumblr/colossus/blob/master/colossus/src/main/scala/colossus/core/server/Server.scala#L75):

```
ssc.setOption(StandardSocketOptions.SO_REUSEADDR, true)
```

(but make it configurable)

**Comment by dxuhuang** [comment]
@DanSimon Did you find anything else we should make configurable?

**Comment by dxuhuang** [comment]
added this to `ServerSettings`. If this is absent in the config, it will be set to the system's default.
