### ISSUE TITLE
Have metric for commands executed in service client implementations

### ISSUE THREAD

**Issue by benblack86** [tumblr/colossus#513]
Suggested by @amotamed

**Comment by DanSimon** [comment]
Is this somehow different from the [client-requests](https://github.com/tumblr/colossus/blob/master/colossus/src/main/scala/colossus/service/ServiceClient.scala#L174) metric that already exists?

**Comment by benblack86** [comment]
The idea was to have a more detailed metric than just # of requests. It would be broken by down by type of request. For example, in redis it would be tagged by command (https://redis.io/commands).

**Comment by DanSimon** [comment]
Ah ok, yeah this should be doable using the [TagDecorator](https://github.com/tumblr/colossus/blob/master/colossus/src/main/scala/colossus/service/ServiceClient.scala#L154).  Sounds like we'd just implement one for each protocol.
