### ISSUE TITLE
Service client changes

### ISSUE THREAD

**Issue by benblack86** [tumblr/colossus#521]
# Problem

Load balancing is currently done by explicitly creating a `LoadBalancingClient` and then using the `CodecClientFactory` (e.g. `Redis.client.apply(sender: Sender[P, M]`) to "lift" the client in to the appropriate client type (e.g. `RedisClient`).

```
val generator = (address: InetSocketAddress) => {
  Redis.client(address.getHostName, address.getPort)
}

val addresses                 = List.fill(3)(new InetSocketAddress("localhost", 6379))
val loadBalancingRedisClients = new LoadBalancingClient[Redis](worker, generator, 3, addresses)
val redisClient               = Redis.client(loadBalancingRedisClients)
```

I think it would be more user friendly if the client handled load balancing itself with a configurable retry policy. It should work for callbacks and futures.

```
Redis.client(addresses, RetryPolicy.RoundRobin(max = addresses.lenth, expoentialBackoff = true))
```

# Notes from previous conversations
- Add retry into on the serviceclient (separate for now, tbd later)
Yes, I think the way to do this is add a new config setting like "maxRetries" to ClientConfig, and then create a "RetryFilter" that extends Sender and wraps the client that is currently created.
- Add loadBalancingClient to LiftedClient (or similar location)
So I think what we want to do here is create a ClientFactory for LoadBalancingClient.  This factory would require a regular client factory as a constructor param or something like that.  Then you can do something like Http.loadBalancingClient
- Concept of filters to be applied to the send command (decorator)
So I think here we need to determine if this needs to be anything more than just a class that extends Sender and takes another sender as a constructor parameter.  Right now I don't think so, which means we already have everything we need to add filters.  Maybe there's some kind of DSL we would build around this, but it's not apparent that we need this.
- Have the LBC expose a hostManager for client manipulation
So the idea here is the LBC doesn't expose a HostManager, but rather it requires one as a constructor parameter.  So you as the user would first create your own HostManager, pass it in when creating the LBC, and the result from that would just be a HttpClient (or whatever protocol you're using).  So you don't interact with LBC directly to change the hosts, but instead through the HostManager that you created.  If this isn't clear I'll write up some code examples.
- Possibly have an error if only one client is passed to the LBC?
Interesting, I can see pro's and cons to this.  Actually....now that I think about it we probably don't want to do that.  For example maybe you have a situation where on startup you only have one host to connect to, but later on (like from config polling), you add more.  We don't want to forbid something like that.
- Maybe have a convenience function called maxPossibleRetries that'll take the host size and the retry size and give you the min (for troubleshooting in config environments), this could be overkill.
Definitely something that can go on HostManager, but like I said we won't be able to add any methods to LBC itself since it'll just be a Sender

**Comment by DanSimon** [comment]
I agree with most of that (I think I wrote some of it lol!).

So all of the lifting stuff should stick around, but ideally we can abstract it all away from the user.  Maybe if a user wants to write their own module or filter, they can then use the lifting to build their own API around it.  But I totally agree that a regular application developer should not need to deal with it.

### Load Balancing via Constructor and/or Mixin

What I think is possible is that, for example with the `RedisClient` constructor, we could have two constructors.  One takes in a single host/port, and another takes in a `HostManager` as described above.  The first would just create a single client while the second would create a load-balanced client:

```scala
//create a simple client
val client1: RedisClient = Redis.client("localhost", 6379)

//create a HostManager
val manager = new HostManager
manager.addHost("localhost", 6380)
val client2: RedisClient = Redis.client(manager)
manager.addHost("localhost", 6381) //sets up new connection under the hood
```
Under the hood this would create a LBC (which would take in the host manager as a constructor param) and lift it into a RedisClient.

It would be tempting to eliminate the first option and just make every client load-balanced, even when you only have one host, but I would like to avoid that if possible.  LBC does add some overhead and if eventually we create other type of modules like LBC, we don't want to always bake them all in.


### Retries

I definitely think retries should be done via a filter.  This is now possible to do in 0.9.0, though there is not yet a formalized notion of a "filter".  But basically it would just be a trait that implements `Sender` and wraps another Sender.  When the ClientFactory is creating the client, it can see if `retries` is > 0 and if so, wrap the client in a retry filter before it gets lifted.  The filter then just flatMaps on incoming requests to do retries/backoffs.

### Final Thoughts

Load balancing and retries offer two use cases for augmenting a client.  I hope we can figure out a solution that can address these cases in a somewhat generic fashion, so any other plugins/modules we create won't require so much work.

**Comment by benblack86** [comment]
I hacked together some basic code that I think does what you explained with the hostmanager and loadbalancer concepts: https://github.com/tumblr/colossus/compare/develop...sc?expand=1

I didn't understand the retry filter idea. At least with a load balancer, I think the standard strategy for a particular request is to iterate over each client until one works or none are left. To do that, the filter would need to keep track of which client has been sent to (or be able to generate a list to try).

**Comment by DanSimon** [comment]
Yeah that code mostly reflects what I was thinking.  

The retry filter is for when you want to do retries without a load-balancer.  I know I've had conversations in the past about trying to pull retries out of the load-balancer so you could do just load-balancing, just retries, or both together.  The problem is as you said though, you need a way to keep track of tried hosts per request.  The solutions I've thought of seem really messy, so I don't think that's the way to go.

So I see two options:

2.  Forget about trying to separate out retries.  So even if you're just connecting to one host over one connection, if you want retries you have to use a load-balancer.  In which case I'd say the name "Loadbalancer" isn't even accurate anymore, and we should think of a different name, maybe something like "RichClient"......This also starts to lead me to believe that maybe we _should_ make this layer a part of every client by default, since it seems like more often than not you're going to want this stuff. 

3.  Have a separate retry filter for single connections, but try to minimize code duplication.  This is what I was originally thinking to do.

**Comment by benblack86** [comment]
I'm leaning on having this layer on every client. We could have a special HostManager class that is used when there is only one host with no retries, which effectively would call directly to the underlying client with no extra logic. Therefore, we would only be adding one extra method call. Maybe the JVM is smart enough to compile that away :)

**Comment by benblack86** [comment]
Having thought about it more, we effectively would still allow the user to create a "one host, no retries" client, so there is no need for an extra layer. If the user wants "one host, x retries" then there has to be an extra layer with logic.

**Comment by DanSimon** [comment]
@benblack86 yep that's pretty much what I'm thinking.  All of this logic should be able to be done inside the client factory and be transparent to anyone creating a client.
