### ISSUE TITLE
Remove akka agent from IOSystem

### ISSUE THREAD

**Issue by benblack86** [tumblr/colossus#529]

**Comment by DanSimon** [comment]
So once upon a time I definitely had a branch where I did this.  I just replaced the agents with AtomicReference's and it all worked fine.  Same for all the other places as well.  Should be pretty easy.

**Comment by benblack86** [comment]
Yeah, just wanted to split work up so multiple people can enjoy the fun :)

**Comment by benblack86** [comment]
https://github.com/tumblr/colossus/pull/532
