### ISSUE TITLE
Use GitFlow for development

### ISSUE THREAD

**Issue by benblack86** [tumblr/colossus#547]
Yo, @DanSimon, we are thinking of trying out the "GitFlow" approach to managing branches:

https://datasift.github.io/gitflow/IntroducingGitFlow.html

Therefore, version will follow the format: Major.minor.hotfix, which will mean more minor versions and less hotfix versions.

The plan is to release 0.9.1 by the end of the week (already have 0.9.1-RC1 published and running) and then we start following GitFlow.

**Comment by DanSimon** [comment]
Yeah I think that's the direction we've been moving towards.  We will just need to be more careful about properly grouping issues into feature branches.  

My thinking is we'll want to treat feature branches kind of like how we currently treat develop.  In other words, when beginning work on a new feature, you create an empty branch called `feature/super-cool-new-feature`.  Then you open PR's into the feature branch.  We'd setup travis to run on any `feature/*` branch.  This way we can still break large tasks into smaller PR's, but not merge into develop until it's all done.  I guess for smaller tasks just opening the PR to develop is fine as long as it's for the next release.

I propose we make this issue into RFC (or open a new one) to get this all down in writing, and once we're all agreed we can just make it part of the contributing.md file.  It should be detailed enough so somebody brand new to the project knows what to do.
