### ISSUE TITLE
Package name should match directory

### ISSUE THREAD

**Issue by benblack86** [tumblr/colossus#555]
For example, HttpServer.scala contains HttpServer object (with other classes) and has package setup:

```
package colossus
package protocols.http
package server
```

However, the file is located in `colossus/protocols/http` directory. I find the multiple package statements confusing as it makes it harder to know where stuff is coming from. Not matching the directory means it is harder to know where to find a file. Thoughts?

**Comment by benblack86** [comment]
FYI @aliyakamercan verbal agreed with this

**Comment by DanSimon** [comment]
Agreed, and this definitely fits in with overall library re-organization #410 .  Hopefully we can get it all done in a single release.
