### ISSUE TITLE
Adding functionality to specify which IP address will be bind to when starting the server.

### ISSUE THREAD

**Issue by andwxh** [tumblr/colossus#624]
Hi all,

It seems currently the IP address is hard coded([here](https://github.com/tumblr/colossus/blob/99c76e710257bcb075db8d4bb52cb8861efac49a/colossus/src/main/scala/colossus/core/server/Server.scala#L114)) when you was trying to start a server.

It will be better if I can specify which IP addresses will be binded when I have multiple IP address on my server.

Would you mind to add this functionality to colossus?

**Comment by benblack86** [comment]
Sounds doable. We should be able to make this an optional piece of config, just like we have `so-reuse-address`.
