### ISSUE TITLE
Colossus doesn't check existence of Host header

### ISSUE THREAD

**Issue by aliyakamercan** [tumblr/colossus#644]
https://tools.ietf.org/html/rfc7230#section-5.4

**Comment by benblack86** [comment]
Just for my understanding, why is it useful?

**Comment by benblack86** [comment]
If I understand the spec correctly, it is a MUST for the client to send. However, it doesn't say it is a MUST for the server to check for the existence.

**Comment by aliyakamercan** [comment]
It's not a valid HTTP req if it is not there. It is a spec thing.

**Comment by benblack86** [comment]
Closing for now since we don't care
