### ISSUE TITLE
Revisit how we handle http headers

### ISSUE THREAD

**Issue by dkarivalis** [tumblr/colossus#649]
Currently it is possible to define a "Content-Type" header in three different ways:

1) `req.ok(json, HttpHeaders(HttpHeader("Content-Type", "application/json")))`
2) `req.ok(json).withContentType("application/json")`
3) set the `contentType` val in an `HttpBodyEncoder`

setting all 3 for a route results in:
<img width="266" alt="screen shot 2017-12-06 at 1 58 54 pm" src="https://user-images.githubusercontent.com/6476505/33687774-0a628c50-da8e-11e7-94b7-905743852afa.png">

a possible solution is to:

A) have a set of header names that are reserved as single value ("Content-Type", 'Content-Length", "Date"?). re-setting a reserved header name overwrites the previous value

B) for all other header names, setting a field name multiple times combines the values in to a comma separated list (as defined in [RFC 2616](https://tools.ietf.org/html/rfc2616#section-4.2))

**Comment by benblack86** [comment]
Does the http spec say these headers can only appear once?

**Comment by benblack86** [comment]
If I read the spec correctly, it does not say that certain headers can only appear once. In fact the content-type exampled showed two values (separated by comma).

There doesn't seem to be a preference between whether the same field should result in a comma separated listed or just repeated. Either way, it should behave the same. Currently headers is a list, but we could change it to a map of string to list, which would make look up quicker. Maybe we should do that for performance reasons?

**Comment by DanSimon** [comment]
Headers used to be a `Map[String, Seq[String]]`, but maps (and basically all scala collections) are unfortunately very slow.  I would advise not moving away from the Java List, as last time I benchmarked it was significantly faster than everything else.

I don't think I benchmarked lookup time, but honestly I wouldn't be surprised if scanning the list is still faster than a map lookup.  Of course we're talking about an O(n) vs an O(1) operation, but I think you'd need to have a lot of headers for that to actually become significant.  But don't take my word for it, definitely would be nice to get some documented numbers on it.  Maybe a java HashMap would work.

**Comment by benblack86** [comment]
I don't think there is any critical need to change this at the moment. At the very least it might make sense to wait for the new scala collections to come out. Once we get better at the habit of benchmarking we can look at this again. Closing for now.
