### ISSUE TITLE
maxResponseSize in Future Clients effectively limited to 10 MB by bytes Parser

### ISSUE THREAD

**Issue by ksajme** [tumblr/colossus#656]
Construction of a Future Client by ClientFactories with an arbitrary maxResponseSize given in a ClientConfig is possible but an exception will be thrown if a response greater than 10 MB is received.
https://github.com/tumblr/colossus/blob/master/colossus/src/main/scala/colossus/util/Parsing.scala#L304

This is due to the following overload which limits the bytes parser to 10 MB:
https://github.com/tumblr/colossus/blob/master/colossus/src/main/scala/colossus/util/Parsing.scala#L323

**Comment by jlbelmonte** [comment]
Thanks for the report @ksajme. I will look into this.
