### ISSUE TITLE
Obligatory example on page

### ISSUE THREAD

**Issue by wibisono** [tumblr/colossus#674]
I managed to run the first example on [docs](http://tumblr.github.io/colossus/0.11.0/index.html) only after changing request handler line into:
```
case request @ Get on Root => Callback.successful(request.ok("Hello world!"))
```
With the callback successful. No big deal but rather bumpy first experience.

**Comment by dkarivalis** [comment]
hey @wibisono! quickly tested the hello world example and am not seeing the same results:
<img width="600" alt="screen shot 2018-11-02 at 11 01 20 am" src="https://user-images.githubusercontent.com/6476505/47923114-f1e77400-de8e-11e8-87c3-73177724471d.png">

which scala / sbt version are you using?

**Comment by wibisono** [comment]
Hi,

Maybe that's the issue, I am using sbt 1.2.6 and scala 2.12.7:
https://imgur.com/a/P1P7iCY

**Comment by wibisono** [comment]
That works :) sorry for the trouble, thanks.
