### ISSUE TITLE
Pull #672 request needs to be reviewed 

### ISSUE THREAD

**Issue by lxohi** [tumblr/colossus#677]
Hey guys,
Is this project still maintained?
Please take some time to review this PR: https://github.com/tumblr/colossus/pull/672
This issue causes problems in non-ascii environments.

**Comment by dkarivalis** [comment]
my apologies for the delay - thank you for your contribution. am reviewing now! :)

**Comment by lxohi** [comment]
Hi, I'm really happy this top of the line framework is still under maintained :P

**Comment by dkarivalis** [comment]
let's change that ^_^
