### ISSUE TITLE
Inactivity

### ISSUE THREAD

**Issue by bpmason1** [tumblr/colossus#680]
The last commit to the master branch for Colossus wad in November if 2018 and the last official release wad much earlier than that.  Is that project still supported or maintained?

**Comment by plokhotnyuk** [comment]
@dkarivalis
@benblack86

Please merge missing changes from the `master` to the `develop` branch

**Comment by dkarivalis** [comment]
we've merged the missing changes from `master` to `develop`

**Comment by rmilejcz** [comment]
Yep I'm wondering this as well, compared to other web service frameworks for Scala this is by far the most developer friendly (I say this as a newbie to scala who spent hours with finagle / finch, spray, http4s etc) and seems to be the fastest as well. I'm not sure that I could contribute much to this library codewise (I am a Scala newbie) but I'm more than happy to help however I can
