### ISSUE TITLE
Graceful Shutdown for Servers

### ISSUE THREAD

**Issue by DanSimon** [tumblr/colossus#77]
Right now there's really no way to gracefully shutdown a Server.  We can close individual connections gracefully, but we should be able to have Servers stop listening for new connections while properly waiting for open connections to either close on their own or timeout.

**Comment by CaptPhunkosis** [comment]
:+1:

**Comment by DanSimon** [comment]
Planning on implementing this soon, here's the details.

We recently solidified the behavior that when a Server unregisters itself from a Worker, the worker will forcibly close any connections associated with the server.  This means gracefully shutting down a server is a 3 step process:

1.  The Server closes the socket, preventing any new connections from being accepted.  However it does not unregister with the IOSystem yet, and it enters a timeout loop where it checks how many open connections still exist.
2.  The server somehow signals to every associated open connection that it is shutting down and connections should stop processing new requests and gracefully disconnect.
3.  Either when the number of open connections hits 0, or when the timeout is reached, the server unregisters itself.

Step 2 is not required, but seems like a good idea, however it requires some thought.  We need a way to signal to server connections to request them to shut down, but without doing anything so drastic as actually calling `connectionTerminated`.  This may actually require a new `ConnectionHandler` method, maybe something like `requestClose(timeout)`, where `timeout` indicates approximately how long the connection has until it get axed.

**Comment by DanSimon** [comment]
So we can solve point 2 by having the server broadcast a new message to the workers, who then call `gracefulDisconnect` on all the server's associated connections.
