### ISSUE TITLE
Integrate with Typesafe Config

### ISSUE THREAD

**Issue by nsauro** [tumblr/colossus#8]
We need to have an external configuration system in place.  Configuration options right now for the Server are fairly small, but will grow.

**Comment by DanSimon** [comment]
So the basic idea is we want to be able to create an `IOSystem` with either just a path location for all config or a config object.  From that point all configuration is pulled from there, eliminating the need to manually pass in config objects when creating services/metrics/clients.

**Comment by nsauro** [comment]
done! w00t!
