### ISSUE TITLE
Is it possible to mark requests as no response needed?

### ISSUE THREAD

**Issue by fehmicansaglam** [tumblr/colossus#80]
I am developing a Mongo codec for Colossus. As you might already know most of the requests to MongoDB don't return a response. Is there a way to manage this workflow. Maybe a callback which is called after request is sent?

**Comment by nsauro** [comment]
It's a been a short while since I've worked with Mongo..can you provide some more details?  
By no response, do you mean no data in the response?

**Comment by fehmicansaglam** [comment]
Not actually. Most of the mongo requests are fire and forget. Client sends an insert message and recieves nothing back. 

You can read more from here: http://docs.mongodb.org/meta-driver/latest/legacy/mongodb-wire-protocol/#op-update

**Comment by nsauro** [comment]
Well, that's a fun document.  Looks like the majority of the cases don't return responses.  I wasn't able to find this in writing, but it hints that the requests are multiplexed..ie, the order of query responses won't necessarily match the order of queries.

So, @DanSimon is the person's input you really want on this, but I will go out and say, in the current version of Colossus, I'm not sure how possible it is to implement a Codec for a protocol which contains both multiplexed and optional responses.   If it is possible, it most certainly won't be straight forward.

What version of Colossus are you developing this for?  Version .6, which is in the works, we started adding a new Controller layer to allow for alternative read/write mechanics.  It was built with streaming in mind, but was written with the intended purpose of eventually supporting alternative mechanics, like multiplexing, etc.

**Comment by fehmicansaglam** [comment]
It's just a hobby project and I am developing on the master branch. Although I have seen the patch for streaming, I haven't read all the source code yet. So at first I should try to understand the mechanics for streaming. Thanks.

**Comment by nsauro** [comment]
Ya...so to kind of get an idea of how it could (possibly) work, you should take peek at ServiceClient and Controller.

ServiceClient.send is a great place to start, because it will take you on a nice tour through the ServiceClient and Controller classes.

I'll be happy to answer any questions or help brainstorm :)

**Comment by mayflaver** [comment]
I think you should  take a look at AsyncHandler, ActorHandler and Worker first, those include most information about asyncClient you want to know, I hope it would help you.

**Comment by fehmicansaglam** [comment]
The new write commands in 2.6 do actually return a response: http://engineering.foursquare.com/2014/04/08/looking-forward-to-mongo-2-6-a-deep-dive-into-the-new-write-commands/ 

I am going to use them for the time being. And one more question. Do you encourage or discourage connection pooling?

**Comment by nsauro** [comment]
There is a LoadBalancingClient, which will maintain a pool of clients.  Take a peek at that.

**Comment by fehmicansaglam** [comment]
Hi again. I am almost finished with the Mongo protocol. Would you consider merging it to master? If so I can send a PR after it is finished.

The only missing thing for the time being is reading over cursors. Is there an example for how to read from remote streams?

**Comment by nsauro** [comment]
I don't see why not.  Dan is on vacation for the upcoming week, so while I can do an initial review and feedback, we probably won't be able to merge until he returns.

**Comment by mayflaver** [comment]
I add a websocket support and also need an initial review

**Comment by nsauro** [comment]
Ok, a PR would be great to get things rolling.
