### ISSUE TITLE
Pipe's semantic for throwing exception when pushing on a finished pipe

### ISSUE THREAD

**Issue by nsauro** [tumblr/colossus#82]
I don't think these are exceptional cases, and I would consider them part of the normal workflow, especially as it is expected that the pipe will be controlled/closed from outside of the controller.

We should just have additional PushResult states for this, instead of exceptions.

Easy to update, but we probably just want to think this through a bit before doing it.

**Comment by nsauro** [comment]
We should also update the behavior of a Controller when receiving a PipeClosedException, as that should close the client, since it will now be in a bad state.

**Comment by DanSimon** [comment]
This was fixed in #125
