### ISSUE TITLE
Mysql Protocol support

### ISSUE THREAD

**Issue by mayflaver** [tumblr/colossus#86]
I wonder if someone finished  a mysql procotol. I did a project based on colossus and I need mysql protocol support. If someone finished it, please give me a hand, if not, I would do it.  ^_^

**Comment by hepin1989** [comment]
+1

**Comment by DanSimon** [comment]
This is definitely on our list of things to do.  Currently we're using plain old JDBC through actors, having native MySQL support in colossus, at least for basic queries, is a priority for us.
