### ISSUE TITLE
Expose ConnectionInfo

### ISSUE THREAD

**Issue by nsauro** [tumblr/colossus#93]
There is no way for me to get a list of what Workers are connected to.  Well, the code is all there, but inaccessible to the outside world.  Would be swell to have this exposed.

**Comment by DanSimon** [comment]
There is the `GetConnectionInfo` message that you can send to the worker manager, but it's not well documented and can probably be improved.

**Comment by nsauro** [comment]
It is private to Colossus, so we just need to modify that access, and maybe just make sure the API makes sense.
